[build]
  command = "pnpm astro build"
  publish = "dist"  

[context.production.environment]
  PNPM_VERSION = "9.15.3"  

[build.environment]
  NODE_VERSION = "v22.2.0" 

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
