backend:
  name: git-gateway
  branch: main # Cambia esto si tu rama principal tiene otro nombre
media_folder: "static/uploads"
public_folder: "/uploads"
collections:
  - name: "publicaciones"
    label: "Publicaciones"
    folder: "src/content/publicaciones"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Enlace", name: "link", widget: "string" }
